[build]
publish = "dist"
command = "npm run build"

# Production settings for main branch
[context.production]
command = "npm run build"

# Settings for stage branch
[context.stage]
command = "npm run build:stage"