# netlify.toml
[dev]
  # Redirect all requests to the identity widget
  command = "npm run serve" # Command to start your Vue dev server
  port = 8080               # Default port used by Vue CLI
  targetPort = 8080

[[redirects]]
  from = "/.netlify/identity"
  to = "http://localhost:8080/.netlify/identity"
  status = 200
  force = true