local_backend: false

backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  # Collection for Navigation Settings for English
  - label: "Navigation Settings (EN)"
    name: "navigation_en"
    files:
      - label: "English Navbar Content"
        name: "navbar_en"
        file: "public/content.json"
        fields:
          - label: "Navbar Main (EN)"
            name: "en"
            widget: "object"
            fields:
              - label: "Items"
                name: "navbarMain"
                widget: "object"
                fields:
                  - label: "Items"
                    name: "items"
                    widget: "list"
                    fields:
                      - label: "Item Label"
                        name: "label"
                        widget: "string"
                      - label: "Item URL"
                        name: "url"
                        widget: "string"
                  - label: "Scrolling Text"
                    name: "scrollingText"
                    widget: "text"
