local_backend: false

backend:
  name: git-gateway
  branch: main

media_folder: "public/img"
public_folder: "/img"

collections:
  - label: "Navigation Settings"
    name: "navigation"
    files:
      - label: "English Navigation Content"
        name: "navbar_en"
        file: "public/content/navbar.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - label: "Scrolling Text"
                name: "scrollingText"
                widget: "text"
              - label: "Navbar Items"
                name: "items"
                widget: "list"
                fields:
                  - label: "Item Label"
                    name: "label"
                    widget: "string"
                  - label: "Item URL"
                    name: "url"
                    widget: "string"

  - label: "Location Banner"
    name: "location_banner"
    files:
      - label: "Location Banner Content"
        name: "location_banner_content"
        file: "public/content/locationBanner.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Address"
                name: "address"
                widget: "string"
              - label: "Business Hours"
                name: "businessHours"
                widget: "string"
          - label: "Norwegian Content"
            name: "no"
            widget: "object"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Address"
                name: "address"
                widget: "string"
              - label: "Business Hours"
                name: "businessHours"
                widget: "string"

  - label: "Location Information"
    name: "location_information"
    files:
      - label: "Location Content"
        name: "location_content"
        file: "public/content/company-info.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Google Maps URL"
                name: "googleMapsUrl"
                widget: "hidden"
              - label: "Address"
                name: "address"
                widget: "object"
                fields:
                  - label: "Header"
                    name: "header"
                    widget: "string"
                  - label: "Street"
                    name: "street"
                    widget: "string"
                  - label: "House Number"
                    name: "houseNumber"
                    widget: "string"
                  - label: "Zip Code"
                    name: "zipCode"
                    widget: "string"
                  - label: "City"
                    name: "city"
                    widget: "string"
              - label: "Social Media Header"
                name: "socialMediaHeader"
                widget: "string"
              - label: "Social Media"
                name: "socialMedia"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Icon"
                    name: "icon"
                    widget: "hidden"
                  - label: "URL"
                    name: "url"
                    widget: "string"
          - label: "Norwegian Content"
            name: "no"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Google Maps URL"
                name: "googleMapsUrl"
                widget: "hidden"
              - label: "Address"
                name: "address"
                widget: "object"
                fields:
                  - label: "Header"
                    name: "header"
                    widget: "string"
                  - label: "Street"
                    name: "street"
                    widget: "string"
                  - label: "House Number"
                    name: "houseNumber"
                    widget: "string"
                  - label: "Zip Code"
                    name: "zipCode"
                    widget: "string"
                  - label: "City"
                    name: "city"
                    widget: "string"
              - label: "Social Media Header"
                name: "socialMediaHeader"
                widget: "string"
              - label: "Social Media"
                name: "socialMedia"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Icon"
                    name: "icon"
                    widget: "hidden"
                  - label: "URL"
                    name: "url"
                    widget: "string"

  - label: "Menu Items Information"
    name: "menu_items_information"
    files:
      - label: "Menu Items Content"
        name: "menu_items_content"
        file: "public/content/products.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - label: "Header for Starters"
                name: "header01"
                widget: "string"
              - label: "Header for Main Dishes"
                name: "header02"
                widget: "string"
              - label: "Teaser for Starters"
                name: "teaser01"
                widget: "string"
                required: false
              - label: "Teaser for Main Dishes"
                name: "teaser02"
                widget: "string"
                required: false
              - label: "Allergen Label"
                name: "allergenLabel"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Category"
                    name: "cat"
                    widget: "select"
                    options:
                      - "starter"
                      - "main"
                      - "dessert"
                  - label: "Price"
                    name: "price"
                    widget: "number"
                  - label: "Ingredients"
                    name: "ingredients"
                    widget: "list"
                    field:
                      label: "Ingredient"
                      name: "ingredient"
                      widget: "string"
                  - label: "Allergens"
                    name: "allergens"
                    widget: "object"
                    fields:
                      - label: "Has Gluten"
                        name: "hasGluten"
                        widget: "boolean"
                        required: false
                      - label: "Has Soya"
                        name: "hasSoya"
                        widget: "boolean"
                        required: false
                      - label: "Has Fish"
                        name: "hasFish"
                        widget: "boolean"
                        required: false
                      - label: "Has Onion"
                        name: "hasOnion"
                        widget: "boolean"
                        required: false
                      - label: "Has Garlic"
                        name: "hasGarlic"
                        widget: "boolean"
                        required: false
                      - label: "Has Mushroom"
                        name: "hasMushroom"
                        widget: "boolean"
                        required: false
                      - label: "Has Shellfish"
                        name: "hasShellfish"
                        widget: "boolean"
                        required: false
                      - label: "Has Sesame"
                        name: "hasSesame"
                        widget: "boolean"
                        required: false
                      - label: "Has Nuts"
                        name: "hasNuts"
                        widget: "boolean"
                        required: false
                      - label: "Has Lemon"
                        name: "hasLemon"
                        widget: "boolean"
                        required: false
                      - label: "Has Lactose"
                        name: "hasLactose"
                        widget: "boolean"
                        required: false
          - label: "Norwegian Content"
            name: "no"
            widget: "object"
            fields:
              - label: "Header 1"
                name: "header01"
                widget: "string"
              - label: "Header 2"
                name: "header02"
                widget: "string"
              - label: "Teaser 1"
                name: "teaser01"
                widget: "string"
              - label: "Teaser 2"
                name: "teaser02"
                widget: "string"
              - label: "Allergen Label"
                name: "allergenLabel"
                widget: "string"
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Category"
                    name: "cat"
                    widget: "select"
                    options:
                      - "starter"
                      - "main"
                      - "dessert"
                  - label: "Price"
                    name: "price"
                    widget: "number"
                  - label: "Ingredients"
                    name: "ingredients"
                    widget: "list"
                    field:
                      label: "Ingredient"
                      name: "ingredient"
                      widget: "string"
                  - label: "Allergens"
                    name: "allergens"
                    widget: "object"
                    fields:
                      - label: "Has Gluten"
                        name: "hasGluten"
                        widget: "boolean"
                        required: false
                      - label: "Has Soya"
                        name: "hasSoya"
                        widget: "boolean"
                        required: false
                      - label: "Has Fish"
                        name: "hasFish"
                        widget: "boolean"
                        required: false
                      - label: "Has Onion"
                        name: "hasOnion"
                        widget: "boolean"
                        required: false
                      - label: "Has Garlic"
                        name: "hasGarlic"
                        widget: "boolean"
                        required: false
                      - label: "Has Mushroom"
                        name: "hasMushroom"
                        widget: "boolean"
                        required: false
                      - label: "Has Shellfish"
                        name: "hasShellfish"
                        widget: "boolean"
                        required: false
                      - label: "Has Sesame"
                        name: "hasSesame"
                        widget: "boolean"
                        required: false
                      - label: "Has Nuts"
                        name: "hasNuts"
                        widget: "boolean"
                        required: false
                      - label: "Has Lemon"
                        name: "hasLemon"
                        widget: "boolean"
                        required: false
                      - label: "Has Lactose"
                        name: "hasLactose"
                        widget: "boolean"
                        required: false

  - label: "Allergens Information"
    name: "allergens_information"
    files:
      - label: "Allergens Content"
        name: "allergens_content"
        file: "public/content/allergens.json"
        fields:
          - label: "English Content"
            name: "en"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Allergens"
                name: "items"
                widget: "list"
                fields:
                  - label: "Label"
                    name: "label"
                    widget: "string"
                  - label: "ID"
                    name: "id"
                    widget: "hidden"
                  - label: "Description"
                    name: "description"
                    widget: "text"
          - label: "Norwegian Content"
            name: "no"
            widget: "object"
            fields:
              - label: "Header"
                name: "header"
                widget: "string"
              - label: "Description"
                name: "description"
                widget: "string"
              - label: "Allergens"
                name: "items"
                widget: "list"
                fields:
                  - label: "Label"
                    name: "label"
                    widget: "string"
                  - label: "ID"
                    name: "id"
                    widget: "hidden"
                  - label: "Description"
                    name: "description"
                    widget: "text"
